export const NOTIFICATION_TYPES = {
  ORGANIZATION_MEMBER_REMOVED: 'ORGANIZATION_MEMBER_REMOVED',
  ORGANIZATION_INVITATION_RECEIVED: 'ORGANIZATION_INVITATION_RECEIVED',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
